# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redoc.ly/docs/cli/ for more information.
vBeta/paths/courses.yaml:
  operation-4xx-response:
    - '#/get/responses'
vBeta/paths/categories.yaml:
  operation-4xx-response:
    - '#/get/responses'
vBeta/paths/users.yaml:
  operation-4xx-response:
    - '#/get/responses'
