openapi: 3.0.2
info:
  title: Merkez API Specification
  version: '0.1'
  description: >-
    API Specification for Merkez institute, based on [software requirements
    document](https://whimsical.com/software-requirements-specification-AHLth8LbaqS17rmKiEQAyd).

    This specification is the single source of truth for Merkez REST API. 


    These links are useful to understand the api design:

    1. [RESTful web API
    design](https://learn.microsoft.com/en-us/azure/architecture/best-practices/api-design)

    2. [REST API Best Practices – REST Endpoint Design
    Examples](https://www.freecodecamp.org/news/rest-api-best-practices-rest-endpoint-design-examples/)
  termsOfService: https://www.merkez.com/terms
  license:
    name: GNU General Public License 3.0
    url: https://www.gnu.org/licenses/gpl-3.0.html
  contact:
    name: API Support
    email: support@merkez.com
    url: https://www.merkez.com/support
servers:
  - url: https://dev.merkez.com/v1
    description: Development Server
  - url: https://staging.merkez.com/v1
    description: Staging Server
  - url: https://api.merkez.com/v1
    description: Production Server
paths:
  /auth/login:
    $ref: paths/auth_login.yaml
  /auth/logout:
    $ref: paths/auth_logout.yaml
  /auth/register:
    $ref: paths/auth_register.yaml
  /courses:
    $ref: paths/courses.yaml
  /courses/{courseId}:
    $ref: paths/courses_{courseId}.yaml
  /categories:
    $ref: paths/categories.yaml
  /categories/{categoryId}:
    $ref: paths/categories_{categoryId}.yaml
  /users:
    $ref: paths/users.yaml
  /users/{userId}:
    $ref: paths/users_{userId}.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security: []
